### ISSUE TITLE
Authentication (proxy?) in front of gtfs-api

### ISSUE THREAD

**Issue by abyrd** [catalogueglobal/datatools-server#50]
Currently the frontend talks directly to gtfs-api without going through the backend, and with no authentication. This means the contents of all feeds are accessible to someone who knows the architecture of the system or sniffs the traffic.

**Comment by landonreed** [comment]
This has been somewhat resolved in that all GraphQL queries for GTFS now checked for valid authentication headers. It's still a bit incomplete because all feeds for a given instance all visible to any authenticated user (see FIXME in code below), but the primary concern is mitigated.

https://github.com/catalogueglobal/datatools-server/blob/d954623333d2ae9e2cc842a3504fe2724502dbe3/src/main/java/com/conveyal/datatools/manager/DataManager.java#L206-L207
