### ISSUE TITLE
Docker deployment?

### ISSUE THREAD

**Issue by typhoon2099** [catalogueglobal/datatools-server#77]
Is it possible to deploy this via Docker?

**Comment by abyrd** [comment]
Hello, I've never used Docker myself, but since the whole environment for this server is one self-contained JAR, a Postgres server and a Mongo server, I imagine it could easily be containerized. 

At present the system is still under heavy development and there are only a few deployments so we're not putting a lot of effort into this kind of thing, but it should be possible.

**Comment by typhoon2099** [comment]
Okay, thanks for the response. I'm playing around with getting this set up locally so I thought I'd avoid installing too much stuff. My first stumbling block seems to be that MongoDB needs to be running for tests. I was hoping the package would compile in it's own Maven image and then I could run the JAR form another Java image, but that's not working so I'll have to try another avenue.
